### PR TITLE
code optimizations and small fixes

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by jvanderzande** [comment]
Thanks, do you have a 3 fase inverter, and if so,  does the inverter tooltip look correct?

**Comment by jvanderzande** [comment]
@mirakels , why have you added this code:
`document.getElementById("box_moonphase").addEventListener("click", function() {`
in https://github.com/amrij/zonnepanelen/pull/41/commits/b6c05074cc47d3158a020c01c55def3e985ed358
?

**Comment by jvanderzande** [comment]
I also see that the colors for today and yesterday are changed. Before the commit yesterday was green and today was blue. now yesterday is grey as all other lines and today is green.
**EDIT: Just saw your forum post explaining this one.**

**Comment by mirakels** [comment]
I only have a 1-phase inverter...
Hm, the box_moonphase should not be in... Don't understand how it got there. proibalby forgot to remove the bottom part of the grand diff...
But it doesn't hurt anything I guess.
In my local branch I have separated 'zon' and 'moon' pictures into their own boxes to be able to position them independently ( i have two gaps in my panel setup. one is filled with moon data and the other with sun data ;) )
I'll see if I can get the separated zon/maan code into development so it still resembles the current situation...

**Pull request merged**
