### PR TITLE
New attempt to separate sun/moon boxes

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by jvanderzande** [comment]
I like  your proposal you made in the other PR, to enlarge them together when either one is clicked. Sounds like the way forward as it than stays the same for me. ;-)

**Comment by mirakels** [comment]
Thanks ;)
 So lets apply it !

**Comment by jvanderzande** [comment]
Thanks. :)

**Comment by jvanderzande** [comment]
Only thing that is missing are the changes for the Mobile & tablet in css sections:
@media screen and (max-width:700px) {
@media screen and (max-width:700px) and (orientation:landscape){

for div.box_moonphase {
so mobile& tablet are now incorrect for moonphase.

**Comment by jvanderzande** [comment]
@mirakels , did you see my comment about the missing css definition?

**Comment by jvanderzande** [comment]
Scratch that, a fix is already committed by @amrij.

**Comment by mirakels** [comment]
hah, I already noticed amrij did add some changes for that so i did not givi it any attention anymore.

**Pull request merged**
