### PR TITLE
Various update for PVGis calcualtions and display

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by mirakels** [comment]
> Shorter is not equal to simplifying and this change does not make it simpler as the comments are gone and nobody will know anymore how it works the next time it is looked at. That was the whole reason of making an separate piece of logic per period. I am not in favour of this change.

I think it is. YesI could have added more comments for the changed part. But after first reading the code I did not understand it because of the many if statements and continue and carefully look if the save variable was updated before the 'continue'
The logic now is: assume the month PVGis must be added but check the corner cases (contract month and reporting month) and the out of bounds (i.e. before contract month and after reporting month).  So with 3 if's all 4 possible periods are managed.

PS: why do you use php qualifiers around the comments? Why not just use them as javascript comments?

**Comment by mirakels** [comment]
> I am not in a position to test now, but am pretty sure this will create issues when a lot of movements are made over the panels and then move away from them, as this is how it was before I changed it if I remember correctly. I've stated it already a while ago that sometimes things are there for a reason so let's not forget that!

Adding the 'area' filter actually limits the triggers on mouseout events. Without it the mouseout events on the graphs will also trigger the the paneelCharctl()  while it is not needed there.

If I understand it correctly the code actually could be more explicit by using

        $("area").on('mouseout', function(event) {
               paneelChartcl();
        })

**Comment by jvanderzande** [comment]
I am fully aware of how it works and as stated: this breaks the refresh back to the converter graphs in case several mouseovers are triggered, so it seems the last mouseout() is finished before all mouseover()'s are processed. That was why I changed it. Just tested and could get it to go wrong with this change.

> PS: why do you use php qualifiers around the comments? Why not just use them as javascript comments?

To keep them server side and not download them to the clients.
I am not going to further debate this as I have spent a lot of time getting this to work the way is is without issues and honestly don't need it (nor want it) to be changed, but leave it to @amrij to decide what he wants.

**Comment by amrij** [comment]
I tested and with "area" it went wrong.  The inverter charts did not return by multi mouseover()'s.
Without "area" it always went well.

The forecast changes give the correct values.
These can be implemented as far as I am concerned.

**Comment by mirakels** [comment]
Strange, area works fine with me.
But maybe it is because I removed the setTimeout() in pannelCharctl(). the delay in getting the inverter graphs back was annoying...
Hm, even with the setTimeout it works fine (mozilla on linux) , wll most of the time, it looks as if it fails a few time after refreshing the page.

**Comment by mirakels** [comment]
I'll update the forceast code with some more comments in a bit

**Comment by jvanderzande** [comment]
> Strange, area works fine with me.
> But maybe it is because I removed the setTimeout() in pannelCharctl(). the delay in getting the inverter graphs back was annoying...
> Hm, even with the setTimeout it works fine (mozilla on linux) , wll most of the time, it looks as if it fails a few time after refreshing the page.

The delay is there to avoid flashing up the Converter charts when moving between panels, so needs to stay as well, but might be able to be tweaked a little. I don't see the removal in this PR.

**Comment by mirakels** [comment]
'area' patch removed

**Comment by mirakels** [comment]
> > Strange, area works fine with me.
> > But maybe it is because I removed the setTimeout() in pannelCharctl(). the delay in getting the inverter graphs back was annoying...
> > Hm, even with the setTimeout it works fine (mozilla on linux) , wll most of the time, it looks as if it fails a few time after refreshing the page.
> 
> The delay is there to avoid flashing up the Converter charts when moving between panels, so needs to stay as well, but might be able to be tweaked a little. I don't see the removal in this PR.
 
I just tested with a mouseleave event on the box_zonnepanelen div:

     <div Class="box_Zonnepanelen" id="box_Zonnepanelen" onmouseleave="paneelChartcl()">

And removing the on("mouseout" ...) and the timeout stuff in paneelCharctl()
Seems to work nicely...

**Comment by amrij** [comment]
I tested it and it works well now.

**Pull request merged**
