### PR TITLE
It is nice to be able to zoom the inverter/panel graphs

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by jvanderzande** [comment]
Maybe I am missing something, but how does this work in our setup as I thought you need to Click&Drag to select an X range to zoom, but all it does for me is enlarge the Box_X div and move the redline along the X-Axis?

**Comment by mirakels** [comment]
Here, on firefox on Linux,  it works great. Just press down the button, drag and then release button gives the zoom without enlarging the box. Only when single clicking, without drag,  the graph it will enlarge the box.

**Comment by jvanderzande** [comment]
I have tried Chrome which doesn't work at all and in Edge which works "sort of" as that still shows a enlarged box_div.  It doesn't look like it is properly supported across the generally used browser.
So I am "on the fence" on this change.

**Comment by amrij** [comment]
In Google Chrome, Mircosoft Edge and Mozilla Firefox on Windows 10 it has a conflict with -is-clicked function.
Zooming in and enlarging is carried out at the same time.
With "Reset zoom" the same happens.
I am also not in favor.

**Comment by jvanderzande** [comment]
I am not really against, but merely noticed it not working for me. So I am fine either way (being on the fence) as it is currently already configured for the power_chart, and won't be using it anyways.

**Comment by mirakels** [comment]
Funny, I just tried google chrome on linux and it works fine there too.
Are you using windows or mac?

The zoom capability was It was already enabled in the powerchart since the beginning I guess. By accident I clicked and dragged on that grpah and noticed this behaviour and liked it. So I enabled it for the inverter and panel graphs too (panel graphs is not useful yet as you only see them when hoovering the panel section, but I thinking a change to keep then on the foreground for some time).

If it does not work for you but it may work for many others I don't see why not enable it. You can alwasy just not click and drag.... Otherewise if we kn ow for sure it does not work for certain operating systems we may disabel it for those systems (just like the extra include for windows systems).

**Pull request merged**
