### PR TITLE
fix year/contract totals calculation

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Review by jvanderzande — COMMENTED** [review]
Just out of curiosity: Why is the parseFloat() needed for these values?

**Comment by mirakels** [comment]
without it I get NaN values for the year/contract parts.
And parseFloat is also used when processing  the ajax data for filling the whole ychart (see the AddDataToUtilityChart() function)

(weird though, i thought I added something like this in the commit log...)

**Comment by amrij** [comment]
When using $ .getJSON (), parseFloat () must be applied.
$ .Ajax () is applied here and the eval () function must be used.
Have you used the latest version of live-server-data-electra .........?
I have used the version with parseFloat () and it gives no errors.
As far as I am concerned, this can be applied if this solves some errors.

**Comment by jvanderzande** [comment]
I was wondering the same thing as the NaN issue was resolved by always providing a value for all fields that are expected in the API call in the live-server-data-electraxxxxx.php scripts, but am fine with the extra safeguard.

**Pull request merged**
