### PR TITLE
manly cosmet readbility fixes and afew html code fixes

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by jvanderzande** [comment]
A single reflow wasn't enough, that is why I put 2. Try changing the size of your browser screen.
Highchart will reflow but doesn't do that immediately, so the box around the graph would not properly line up. Open for other suggestions/solutions, but otherwise please leave them in.

**Comment by mirakels** [comment]
In may case it works just fine, even when I clicked multiple graphs and the resize the browser, even while continueosly resizing the window the graphs follow nicely. although a bit lagging after stopping the resize al graphs are properly aligned within a couple of milliseconds.

But otherwise just skip that patch form the pull request for now

**Comment by jvanderzande** [comment]
This is what I mean when it is one reflow. To simulate just press f12 in chrome to "resize" your window:
image

Jos

**Comment by mirakels** [comment]
Strange. I use firefox , but just ttried chrome and it works just fine on both browsers. What my be different is that I use a linux machine (fedora). 

PS: what is the red line?  I do not see them on my graphs...

**Comment by jvanderzande** [comment]
Could you change that reflow commit so we can process the whole PR?
The red line are the PVGis values from the config.php, only when specified, to give you the forecast for the Day/Month. :)
I also have a issue with the change of tabs in de title box of the panelen back to spaces in #37 patch https://github.com/amrij/zonnepanelen/pull/37/commits/f6ff57befa8c6ef958b129e650027ff5bd5a9103
The values aren't aligned anymore, as they were in the beginning. When using Tab's this issue is gone for me.
image 
Also now see there are 2 lines with different values but both say "(max.)".

**Comment by mirakels** [comment]
Hm, I tyhought I actually did convet all the spaces to tabs. They are aligned on my browser. I guess it may have to do with browser specific font rendering. Ideally it would be nice to use a table for that but somehow html tags don't seem to work in tooltips :(

**Comment by jvanderzande** [comment]
Correct, its is rendered by the browser making it limited and can differ in each browser. It can be changed to jquery to be able to format them better and probable also make them more responsive, but I've never looked at it in detail.

**Comment by mirakels** [comment]
so for some it looks good for some a bit less. 
Same thing with the fact that the 'energieleverancier' can have different lengths so the tooltips will be ragged.

I just saw there are still some spaces in there instead of tabs. Will convert it to \t in a next round.

**Comment by jvanderzande** [comment]
Thanks ...  I will revert the reflow patch since the 2 seems to be required to have it properly reflow.

**Pull request merged**
