### PR TITLE
cosmetics

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by jvanderzande** [comment]
Is this issue also fixed in this PR? #6 

Jos

**Comment by mirakels** [comment]
Hi Jos, No it doesn't. I did not see your issue but did notice the problem myself.  
I tried by uing the order DESC but somehow my mysql version does not take that into account. So in my local tree I have fixed this in another way (basically by using two sql queries, one for the min()/max() etc values and one for the last added values).
I can push this in a PR, but I made more changes to to live-...zon.php that were refused bij Andre the fdirst time so no try to achieve this in smaller steps...

**Comment by jvanderzande** [comment]
I have reverted the change for that SQL statement in my current domoticz version of  live-...zon.php here:  https://github.com/jvanderzande/zonnepanelen/commit/689cf9417c1ebbb4829c8bd916477bfa8a3cb1d8
... and think the requests needs to be in 2 steps, as the original was, to ensure the records are first sorted in a DESCENDING order before it is summarized by the group statement. 
Thanks, Jos

**Comment by mirakels** [comment]
Yes Jos, that is the solution in my local tree too (but I think the  select ... from (select ...) can be simplified to a single select ... from ...

**Comment by mirakels** [comment]
Jos can you test the attached version?

[live-server-data-zon.php.txt](https://github.com/amrij/zonnepanelen/files/3020441/live-server-data-zon.php.txt)

**Comment by jvanderzande** [comment]
Just tested and it seems to be looking good! 
Thanks / Dank je :)
Jos

**Comment by amrij** [comment]
Jos,

 

Hierbij mijn versie van zonnepanelen-electra.php. Hierin zijn alle wijzigingen van zonnepanelen.php verwerkt. 

Ik heb in live-server-data-electra-p1_meter_table.php “UsageRetour” toegevoegd om de teruglevering op het scherm te kunnen tonen.

Ik heb de popup’s nog niet aangepast.

 

Groet,

 

André

 

Van: Jos van der Zande <notifications@github.com> 
Verzonden: vrijdag 29 maart 2019 12:17
Aan: amrij/zonnepanelen <zonnepanelen@noreply.github.com>
CC: amrij <a.m.rijkeboer@am-rijkeboer.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [amrij/zonnepanelen] cosmetics (#7)

 

Just tested and it seems to be looking good! 



Thanks / Dank je :)

Jos

**Pull request merged**
