### PR TITLE
separate out sunrise and moonphase in their own box

### PR DESCRIPTION
**Pull request by mirakels**
Useful to place those items independently on the page

### CODE REVIEW

**Comment by jvanderzande** [comment]
I am not sure why we would want that as I do like them in one box together being enlarged as a set, so leave it to @amrij to decide what he wants to do with the PR.

Ones this PR is merged I think we should move everything to the master when we are all happy and the 3 fase layout of the Tooltip is confirmed working by @amrij (could you test this please?).

**Comment by amrij** [comment]
Mous over does not work anymore for all the boxes
3 fase layout of the Tooltip is not working.

**Comment by amrij** [comment]
change color '# 009900' to '# 4169E1' this more clearly

**Comment by amrij** [comment]
click function is only working for the box_Zonnepanelen.

**Comment by jvanderzande** [comment]
> Mous over does not work anymore for all the boxes
> 3 fase layout of the Tooltip is not working.

Guess these are fixed by the change you mailed to me ...right?

**Comment by jvanderzande** [comment]
> change color '# 009900' to '# 4169E1' this more clearly

I will add this change to the commit together with that year bugfix.

**Comment by jvanderzande** [comment]
> click function is only working for the box_Zonnepanelen.

is this when you apply this patch or before, as it is working fine for me without this patch and I am not really in favor of this patch separating the Sun & Moon?

**Comment by mirakels** [comment]
without separating bmoon and sun you can never do things like:

image

And if you really want to enlarge sun and moon together we can change
`        document.getElementById("box_sunrise").addEventListener("click", function() {
                this.classList.toggle("box_sunrise-is-clicked");
        });
        document.getElementById("box_moonphase").addEventListener("click", function() {
                this.classList.toggle("box_moonphase-is-clicked");
        });
`
to

`        document.getElementById("box_sunrise").addEventListener("click", function() {
                this.classList.toggle("box_sunrise-is-clicked");
                this.classList.toggle("box_moonphase-is-clicked");
        });
        document.getElementById("box_moonphase").addEventListener("click", function() {
                this.classList.toggle("box_moonphase-is-clicked");
                this.classList.toggle("box_sunrise-is-clicked");
        });
`

I'll create a configurable option for that in a new pull request

**Pull request closed without merging**
