### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by mirakels**

### CODE REVIEW

**Comment by jvanderzande** [comment]
This PR can't be merged yet as one of the commit contains the removal of the graph reflows, which are required as far as I remember for proper sizing of the graphs in case the screen was resized since the start

**Comment by mirakels** [comment]
The reflow is also moved to the paneelFillSeries() function.
Do you mean the redraw? Is that needed whe a reflow is already done?

**Comment by jvanderzande** [comment]
> The reflow is also moved to the paneelFillSeries() function.
> Do you mean the redraw? Is that needed whe a reflow is already done?

mmm ... strange you remove it when not knowing for 100% whether it is needed or not. ;-)
To my knowledge we are doing AddPoint() with the redraw parameter set to false, so would think one needs to fire the redraw operation when all points are added. The reflow only does an extra sizing operation as the redraw doesn't always make it properly fit to the defined DIV box.
Either way: My vote goes to : "If it aint broke don't fix it" when not being 100% sure when it comes to these kind of things. 

ps: You are of course right about the reflow just being moved. :)

**Comment by mirakels** [comment]
well, it was actually a mistake that a fogot to  move the redraw ;)
And based on your comment I wondered if it would be needed as it does not give problems on my side... 

I;ll add a fix to include the redraw again.

**Comment by mirakels** [comment]
done

**Review by jvanderzande — COMMENTED** [review]
Why is animation changed from 0 to false?  This parameter takes a time in milliseconds and is not a boolean.

**Review by jvanderzande — COMMENTED** [review]
I have tested moving the redraw & reflow to the paneelFillSeries function, but that is causing the expected issues as I indicated earlier. It seems the reflow needs to be done after the DIV is made visible.  Just load the webpage, press F12 to get a different width of the website and hover over the panels to see the issue with this change.

**Comment by mirakels** [comment]
Ah I see now thre are different animations. (chart and series). reverted that patch.

will look at redraw/reflow later.

**Comment by mirakels** [comment]
put reflow back to old location...

**Pull request merged**
